# Please access https://squidfunk.github.io/mkdocs-material for more details.
site_name: OpenProphetDB
site_description: "OpenProphetDB is an open research community dedicated to <b>unlocking the therapeutic potential of existing drugs for patients with rare and complex diseases</b>. We advance precision medicine through the integration of <b>Electronic Health Records</b>, <b>Knowledge Graphs</b>, <b>Multi-Omics Data</b>, and <b>Deep Learning Models</b> to elucidate molecular mechanisms of human diseases and accelerate drug repurposing for unmet medical needs."
site_author: "Jingcheng Yang"
announce: "OpenProphetDB"
announce_text: 'We are looking for partners who are highly motivated on drug repurposing to join the OpenProphetDB community. Please contact us if you are interested.'
docs_dir: docs/
repo_name: "OpenProphetDB"
repo_url: "https://github.com/open-prophetdb"
edit_uri: prophetdb.org/edit/main/docs/
markdown_extensions:
  - meta
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/timeline.css
plugins:
  - search
  - git-revision-date
extra:
  homepage: https://www.prophetdb.org
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/open-prophetdb
      name: OpenProphetDB
  generator: false
copyright: Copyright &copy; 2016 - 2024 OpenProphetDB
theme:
  custom_dir: docs/assets/overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - search.share
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
  favicon: assets/images/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to dark mode
      primary: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  name: "material"

# Table of contents
nav:
  - Home: index.md
  # - Projects: projects.md
  # - Goals: goals.md
  - 'Drug & Target': drug_target.md
  # - 'Platform & Resources': platform.md
  - 'MultiOmics Data': multiomics_data.md
  - 'MultiAgents': multiagents.md
  - Publications: publications.md
  - Team: team_members.md
  - 'Join Us': contact.md
