# Please access https://squidfunk.github.io/mkdocs-material for more details.
site_name: OpenProphetDB
site_description: "OpenProphetDB is a research group which is interested in the following topics: construct and integrate <b>knowledge graph</b>, <b>multi-omics data</b> and <b>deep learning models</b> to find new drug targets and biomarkers, understand the molecular mechanisms of human diseases and toxicants, and develop novel therapeutic strategies. It is led by Jingcheng Yang, Zihan Ran, and Yechao Huang."
site_author: "Jingcheng Yang"
announce: "OpenProphetDB"
announce_text: 'We are looking for highly motivated graduate students, and undergraduate students to join our team. Please contact us if you are interested.'
docs_dir: docs/
repo_name: "OpenProphetDB"
repo_url: "https://github.com/yjcyxky"
edit_uri: prophetdb.org/edit/main/docs/
markdown_extensions:
  - meta
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search
  - git-revision-date
extra:
  homepage: https://www.prophetdb.org
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prophetdb-openlab
      name: OpenProphetDB
  generator: false
copyright: Copyright &copy; 2016 - 2023 OpenProphetDB
theme:
  custom_dir: docs/assets/overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
  favicon: assets/images/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to dark mode
      primary: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  name: "material"

# Table of contents
nav:
  - Home: index.md
  - 'Ongoing Projects': projects.md
  - Goals: goals.md
  - Platform: platform.md
  - Publications: publications.md
  - 'Team Members': team_members.md
  - 'Contact Us': contact.md
  - 'FAQs': faqs.md
