# Please access https://squidfunk.github.io/mkdocs-material for more details.
site_name: OpenProphetDB
site_description: "OpenProphetDB is an open research group focused on <b>unlocking the potential of existing drugs to save patients with rare and complex diseases</b>. We explore the following topics: constructing and integrating <b>knowledge graph</b>, <b>multi-omics data</b>, and <b>deep learning models</b> to understand the molecular mechanisms of human rare and complex diseases, or to predict new indications for known drugs through drug repurposing."
site_author: "Jingcheng Yang"
announce: "OpenProphetDB"
announce_text: 'We are looking for partners who are highly motivated on drug repurposing to join the OpenProphetDB community. Please contact us if you are interested.'
docs_dir: docs/
repo_name: "OpenProphetDB"
repo_url: "https://github.com/open-prophetdb"
edit_uri: prophetdb.org/edit/main/docs/
markdown_extensions:
  - meta
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search
  - git-revision-date
extra:
  homepage: https://www.prophetdb.org
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/open-prophetdb
      name: OpenProphetDB
  generator: false
copyright: Copyright &copy; 2016 - 2024 OpenProphetDB
theme:
  custom_dir: docs/assets/overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
  favicon: assets/images/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to dark mode
      primary: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  name: "material"

# Table of contents
nav:
  - Home: index.md
  - Projects: projects.md
  - Goals: goals.md
  - 'Platform & Resources': platform.md
  - Publications: publications.md
  - 'Team Members': team_members.md
  - 'Contact Us': contact.md

