# Please access https://squidfunk.github.io/mkdocs-material for more details.
site_name: ProphetDB OpenLab
site_description: "ProphetDB OpenLab is a research group in the Department of Molecular and Human Genetics at Shanghai Institute of Health Sciences. It is created by Zihan Ran. The lab is interested in understanding the molecular mechanisms of human diseases and toxicants, and developing novel therapeutic strategies."
site_author: "Jingcheng Yang"
announce: "ProphetDB OpenLab"
announce_text: 'We are looking for highly motivated graduate students, and undergraduate students to join our team. Please contact us if you are interested.'
docs_dir: docs/
repo_name: "prophetdb-openlab"
repo_url: "https://github.com/prophetdb-openlab"
edit_uri: prophetdb.org/edit/main/docs/
markdown_extensions:
  - meta
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search
  - git-revision-date
extra:
  homepage: https://www.prophetdb.org
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prophetdb-openlab
      name: Ran Lab
  generator: false
copyright: Copyright &copy; 2016 - 2023 Ran Lab
theme:
  custom_dir: docs/assets/overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
  favicon: assets/images/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to dark mode
      primary: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  name: "material"

# Table of contents
nav:
  - Home: index.md
  - Projects: projects.md
  - Publications: publications.md
  - 'Team Members': team_members.md
  - 'Contact Us': contact.md
